### PR TITLE
Add wallpaper submissions

### PR DESCRIPTION
**Pull request by bitigchi**
Some source files are zipped to circumvent Github's 100MB size limit.

### CODE REVIEW

**Comment by humdingerb** [comment]
The "Falling Leaf" and "Linear Leaf" variations consist of practically identical images, only differing in colours, outlines etc. I propose to only include one of the big .kra files as source and just keep the PNGs for the variations.
That should save a few hundred MiBs... :)

In the same contributions by Julius Enriquez, we don't need the actual license text, but just the short disclaimer with his copyright and license:

   Haiku Desktop Background   
    [Name-of-the-background]    
    Copyright 2020, [Name-of-the-artist] <emailaddress@something.net>   
    Licensed under CC Attribution-ShareAlike 4.0 International.   
    [Optional additional info]

Can you get those, or shall I look to find his mail address to ask for that?

**Comment by humdingerb** [comment]
Maybe, before you delete the .kra files, export higher resolution PNGs istead of the 1080p previews.

**Comment by bitigchi** [comment]
FYI, I am done with this one. Fine tuning can be done by Haiku developers to make it suit better to repo guidelines.

**Comment by humdingerb** [comment]
I did as stated above with 15e7e23bee5acec03cc83aeccea9fd74af4a9c4d .

**Pull request closed without merging**
