### PR TITLE
Add Beta3 disc artwork

### PR DESCRIPTION
**Pull request by jt15s**
Added new Beta3 disc artwork, redesigned from scratch as an SVG to make editing easier on all platforms.

### CODE REVIEW

**Comment by pulkomandy** [comment]
That makes it nearly impossible to edit in Haiku. I don't think that's a good move. Are we serious about making Haiku a good operating system, or is it just a toy with all the work being done from other OS?

Also:
- There is no cover/sleeve?
- The white on light yellow text is not very readable
- It does not mention that this is Haiku "Release 1". This is important. There will be beta versions of other releases later
- It does not mention "intel compatible", which is also important. This version will not run on other CPU architectures
- Is the background just plain yellow with nothing at all? The previous DVD had some leaves and gradients there

**Comment by jt15s** [comment]
I think the original disk covers weren't of a native Haiku format either - I should have thought about doing it in WB, oops.

The cover/sleeve is still WIP and I was thinking of including some screenshot on there, hence why I have not uploaded it to the repo.

I will add the "Release 1" and "Intel compatible" parts soon.

I thought of changing the background colour to match that of the "Get Haiku" button since it was brighter and stood out more. I'll play around with the gradients and see what I can do.

**Comment by jt15s** [comment]
Working on a WB version right now based on the original design - after some thought it's probably better to go with the tried and tested format.

**Comment by pulkomandy** [comment]
Actually I was thinking of using different colors for different architectures, that could be interesting too (but a bit more work).

**Comment by jt15s** [comment]
Good idea! Maybe 32-bit can remain the same, but 64 bit could use the yellow on the download button?

**Comment by kallisti5** [comment]
Hm... I think you might be too close to the edges.  I know there's a standard margin of a few mm.

**Comment by kallisti5** [comment]
Here's the R1 / Alpha 4 artwork for reference

photo_2021-06-14_10-34-40

**Comment by jt15s** [comment]
Closing this PR since it's gone stale and is no longer necessary since R1B3 disc graphics have already been made and added to the repo.

**Pull request closed without merging**
